### ISSUE TITLE
Missing dependencies trying to run via docker?

### ISSUE THREAD

**Issue by jcnmsg** [jfoclpf/geoapi.pt#109]
I'm trying to run this API directly via docker:

```sudo docker run -p 8080:8080 jfoclpf/geoapi.pt:latest```

And I'm getting the following output:

```
2024-01-30T15:43:08: PM2 log: Launching in no daemon mode
2024-01-30T15:43:08: PM2 log: App [index:0] starting in -fork mode-
2024-01-30T15:43:08: PM2 log: App [index:0] online
Starting. Please wait...
Error: Cannot find module 'cssnano'
Require stack:
- /usr/src/app/src/server/services/webpack.js
- /usr/src/app/src/server/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/usr/src/app/src/server/services/webpack.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/src/server/services/webpack.js',
    '/usr/src/app/src/server/index.js'
  ]
}
2024-01-30T15:43:08: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
```

It appears to be missing some dependencies? Maybe the `RUN npm ci --omit=dev` command on the Dockerfile is ignoring `cssnano` which is needed for production?

**Comment by jfoclpf** [comment]
thank you, I guess you're right, I should move `cssnano` from `devDependencies` to `dependencies` in package.json

I will do that ASAP

**Comment by JbrunoMS** [comment]
Hi jfoclpf. 
Did you fix the docker image?

Thanks

**Comment by jfoclpf** [comment]
I'll do it today evening

João Pimentel Ferreira <https://www.joaopimentel.com>

**Comment by jfoclpf** [comment]
Docker is already working, please tell me if it works on your side

Please consider a small donation if you make money with this, thanks

**Comment by jfoclpf** [comment]
@jcnmsg @JbrunoMS do zou confirm it's working properly?

**Comment by jcnmsg** [comment]
> @jcnmsg @JbrunoMS do you confirm it's working properly?

It's working properly now, thank you very much.

**Comment by JbrunoMS** [comment]
Yes, it's working, thank you. 👍
